### ISSUE TITLE
Issues with collectd 5.1.0

### ISSUE THREAD

**Issue by backbohne** [logstash-plugins/logstash-codec-collectd#18]
Hi,

my inputworker cores after some seconds/minutes when logstash reads UDP packets from collectd 5.1.0 via network from our external collectd server (via proxy forward). 

This behavior will be disappear in case I use my local collectd agent (version 5.4.1) as proxy (forward to 127.0.0.1) as well and switch logstash listener to 127.0.0.1.

OK, collectd 5.1.0 is a bit outdated, but we can not upgrade without test all of our slightly older clients :-(

```
{:timestamp=>"2016-03-21T15:55:37.648000+0100", :message=>"Exception in inputworker", "exception"=>#<TypeError: NilClass can't be coerced into Fixnum>, "backtrace"=>["org/jruby/RubyFixnum.java:361:in `+'", "/opt/logstash-codec-collectd/lib/logstash/codecs/collectd.rb:395:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:96:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:73:in `udp_listener'"], :level=>:error}
{:timestamp=>"2016-03-21T15:57:25.669000+0100", :message=>"Exception in inputworker", "exception"=>#<NoMethodError: undefined method `<<' for nil:NilClass>, "backtrace"=>["/opt/logstash-codec-collectd/lib/logstash/codecs/collectd.rb:395:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:96:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:73:in `udp_listener'"], :level=>:error}
```

I'm using the lasted collectd codec from github with logstash  2.2.2-1.

Regards
Frank

**Comment by untergeek** [comment]
Thanks for the report.  I'm not even sure exactly _why_ it's failing, based on that message.  Since you're reporting that it works with 5.4.1, It may be that the 5.1.0 `typesdb` file is the culprit.  In other words, you're sending in 5.1.0 format, but the codec is expecting 5.4.x, and there may be a conflict.  But when you proxy through 5.4.1, it works (because it's an updated `typesdb` file).

You can specify a 5.1.0 `typesdb` file and see if that changes anything for you.

**Comment by backbohne** [comment]
Sorry forgot to notice, using the original 5.1.0 `typesdb` from our collectd server (in both cases).

here is my logstash config input:

```
  udp {
    host => "127.0.0.1"
    port => 25826
    buffer_size => 1452
    codec => collectd { 
      typesdb => [
        "/opt/logstash/collectd/types.db"
      ]
    }
    type => "collectd"
  }
```
